export const tafys = {
  name: "TAFYS",
  kicker: "Ulaşım ve filo platformu",
  headline: "Planla. Uygula. İzle.",
  lead: "Kurumsal, sürücü ve yolcu tek ekosistemde.",
  chips: ["Web paneli", "iOS ve Android", "Ekim 2026"],
  surfaces: {
    title: "Üç yüzey, tek ekosistem",
    text: "Kurumsal taraf planlar ve yönetir. Sürücü sahada uygular. Yolcu hizmeti tüketir ve izler. Veri merkezi API üzerinden aynı anda güncellenir.",
    items: [
      {
        tag: "Planlar",
        title: "Kurumsal",
        text: "Operasyon, filo, müşteri, personel ve muhasebe. Web paneli ve iOS/Android mobil uygulama.",
      },
      {
        tag: "Uygular",
        title: "Sürücü",
        text: "Atanan seferi başlatır, GPS paylaşır, durak ve yolcu durumunu günceller. Web paneli ve mobil uygulama.",
      },
      {
        tag: "İzler",
        title: "Yolcu",
        text: "Veli, personel ve yolcu servisi, turu ve transferi canlı izler; rezervasyon ve istisna girer.",
      },
    ],
  },
  audience: {
    title: "Kim hangi uygulamayı kullanır",
    headers: ["Karar verici", "İhtiyaç", "TAFYS"],
    rows: [
      ["Firma sahibi, operasyon müdürü", "Filo, sefer ve müşteriyi tek yerden yönetmek", "Kurumsal panel ve mobil"],
      ["Saha sürücüsü", "Günün işini telefonda yürütmek", "Sürücü uygulaması"],
      ["Veli, personel, tur yolcusu", "Aracın nerede olduğunu ve hizmeti görmek", "Yolcu uygulaması"],
    ],
    lines: [
      "Turizm araç kiralama",
      "Tur acenteliği",
      "Araç kiralama",
      "Kurumsal personel servisi",
      "Okul servisi",
      "Tarifeli otobüs ve minibüs",
      "Lojistik sevkiyat",
    ],
  },
  core: {
    title: "Her firmada açık kalan çekirdek",
    text: "Firma sahibi, yönetici, muhasebe ve yetkili personel aynı paneli rolüne göre kullanır. Hangi modülün açık olacağı firma bazında belirlenir.",
    headers: ["Yetenek", "Ne sağlar"],
    rows: [
      ["Özet pano", "Araç, aktif operasyon ve alarm görünümü"],
      ["Canlı takip", "Filonun haritada anlık konumu, hız ve son güncelleme"],
      ["Yetkililer ve sürücüler", "Rol atama, tekli ve toplu sürücü ekleme"],
      ["Müşteri yönetimi", "Kurumsal müşteri, tur yolcusu, okul velisi ve personel; Excel aktarımı"],
      ["Talepler ve raporlar", "Gelen iş, teklif ve operasyon özetleri"],
      ["Vitrin", "Müsait araç ve tur paketleri, teklif ve müzakere"],
    ],
  },
  areas: [
    {
      title: "Operasyon",
      text: "Sefer oluşturma, araç ve sürücü atama, taslaktan tamamlanmaya durum takibi, UETDS senkronu, acente paylaşımı ve teyit.",
    },
    {
      title: "Araç ve filo",
      text: "Envanter, bakım, sigorta ve muayene, belge arşivi, sürücü ataması, alarmlar. Arvento, Mobiliz ve Streamax araç kartında toplanır.",
    },
    {
      title: "Okul servisi",
      text: "Okul, öğrenci ve veli, rota şablonu, canlı sefer, öğrenci durumu, arşiv ve rapor.",
    },
    {
      title: "Personel servisi",
      text: "Müşteri firma, personel, rota, canlı sefer, katılım istisnası, rapor ve Excel aktarımı.",
    },
    {
      title: "Tur ve acente",
      text: "Tur paketi, çıkış planı, rezervasyon, B2B tur ve araç temin teklifi, müzakere.",
    },
    {
      title: "Ön muhasebe ve satış",
      text: "Gelir-gider, kasa, dönem özeti, rezervasyon ve ödeme durumu, kiralama sözleşmesi ve navlun köprüsü.",
    },
  ],
  roles: {
    headers: ["Rol", "Yetki"],
    rows: [
      ["Firma sahibi", "Tam yetki"],
      ["Yönetici", "Operasyon, araç, müşteri ve kiralama"],
      ["Muhasebeci", "Görüntüleme ve muhasebe"],
      ["Personel / firma sürücüsü", "Görüntüleme ve bildirim"],
    ],
  },
  showcase: {
    title: "Vitrinden araç temini",
    steps: [
      "İl ve araç tipine göre müsait araç veya tur seçilir",
      "Operasyon veya tur çıkışına bağlı teklif açılır",
      "Araç sahibi bütçe ve koşul sunar, karşı teklif yürür",
      "Onayda araç ve sürücü bilgisi operasyona işlenir",
    ],
  },
  driver: {
    title: "Sahada uygulanan yetenekler",
    text: "Menü, firmanın açık modüllerine göre görünür. Kapalı modül sürücü uygulamasında da gizlenir.",
    headers: ["Yetenek", "Sürücünün yaptığı"],
    rows: [
      ["Pano", "Yaklaşan seferler, okul ve personel sayaçları, aylık takvim"],
      ["Operasyonlar", "Atanan işin listesi, detayı ve durum filtresi"],
      ["Okul servisi", "Canlı sefer, dinamik rota, durum: alındı, binmedi, bekliyor"],
      ["Personel servisi", "Canlı sefer, durak paneli, durum: alındı, gelmedi, bekliyor"],
      ["Araçlar ve GPS", "Atanmış araçlar, Arvento konumu, canlı paylaşım"],
      ["Lojistik", "Atanan sevkiyat işleri"],
      ["Ön muhasebe", "Gelir ve gider, araç ve operasyon ilişkisi"],
    ],
    flowTitle: "Okul servisi saha akışı",
    flow: [
      { title: "Sefer listesi", text: "Kurumsal rotadan atanan işler gelir." },
      { title: "Sefer özeti", text: "Araç, güzergâh ve duraklar açılır." },
      { title: "Canlı sefer", text: "Harita ve dinamik rota başlar." },
      { title: "Durak paneli", text: "Öğrenci: alındı, binmedi, bekliyor." },
      { title: "GPS paylaşımı", text: "Veli ve yolcu aynı konumu izler." },
      { title: "Geçmiş", text: "Tamamlanan sefer kayıtta kalır." },
    ],
    flowNote: "Aynı model personel servisinde yolcu durumu ile çalışır: alındı, gelmedi, bekliyor.",
  },
  passenger: {
    title: "Hizmeti izleyen ve yöneten taraf",
    text: "Veli, kurumsal servis personeli ve tur yolcusu aynı uygulamayı kullanır. Gördüğü hizmet, kurumsal kayda bağlıdır.",
    headers: ["Sekme", "Yetenek"],
    rows: [
      ["Ana sayfa", "Cüzdan, bilet ve rezervasyon özeti"],
      ["Servislerim", "Okul ve personel servisi, katılım istisnası"],
      ["Canlı takip", "Okul, personel, tur ve transfer tek ekranda. Konum yaklaşık 12 saniyede bir yenilenir"],
      ["Turlar", "Kalkış, koltuk, rezervasyon, ödeme ve devam eden turda canlı araç"],
      ["VIP transfer", "Aktif transferin canlı konumu ve biletleri"],
      ["Profil", "Hesap, kayıtlı yolcular, cüzdan, biletler, sorun bildirimi"],
    ],
    whoTitle: "Kim ne görür",
    whoHeaders: ["Kullanıcı", "Kurumsal kayıt", "Uygulamada"],
    whoRows: [
      ["Veli", "Öğrenci ve veli eşleşmesi", "Servis takibi, istisna, öğrenci geçmişi"],
      ["Personel", "Personel servis kaydı", "Servis detayı ve canlı konum"],
      ["Tur yolcusu", "Tur çıkışı ve operasyon", "Rezervasyon, ödeme, canlı araç"],
      ["Transfer yolcusu", "Transfer operasyonu", "VIP canlı izleme ve bilet"],
    ],
    note: "Otobüs bileti ve araç kiralama ekranları arayüz olarak durur; canlı satış akışına henüz bağlı değildir. Demoda servis, tur ve transfer gösterilir.",
  },
  journey: {
    title: "Aynı iş, üç yüzey",
    headers: ["Senaryo", "Kurumsal", "Sürücü", "Yolcu"],
    rows: [
      ["Okul servisi", "Okul, öğrenci, veli, rota", "Seferi başlatır, durak durumunu işler, GPS açar", "Veli aracı izler, istisna girer"],
      ["Personel servisi", "Firma, personel, rota, rapor", "Yolcu durumunu ve rotayı sahada günceller", "Servisi ve konumu görür"],
      ["Tur", "Paket, çıkış, acente teklifi", "Atanan operasyonu yürütür", "Koltuk seçer, öder, aracı izler"],
      ["Araç temini", "Vitrin, teklif, operasyona bağlama", "Onay sonrası iş listede belirir", "Açık turdan rezervasyon yapar"],
      ["Lojistik", "Yük, durak, irsaliye, navlun", "Sevkiyat işini görür", "Yolcu uygulamasının konusu değildir"],
    ],
  },
  modules: {
    title: "Firma yalnızca kullandığı alanı açar",
    text: "Sürücü ve yolcu menüsü bu açılışa göre şekillenir.",
    items: [
      ["Araç yönetimi", "Envanter, bakım, belge, sürücü ataması, telemetri"],
      ["Filo yönetimi", "Harita, atama, hız, alarm, özet pano"],
      ["Operasyon yönetimi", "Sefer yaşam döngüsü, rota, UETDS, acente teyidi"],
      ["Tarifeli sefer", "Bilet, koltuk, yolcu listesi"],
      ["Tarifesiz sefer", "Serbest biniş, abonelik, günlük özet"],
      ["Hat yönetimi", "Minibüs hattı, sefer saati, kapasite"],
      ["Tur ve acente", "Paket, çıkış, rezervasyon, B2B teklif"],
      ["Okul servisi", "Öğrenci, veli, durak, canlı sefer"],
      ["Personel servisi", "Hat, biniş noktası, istisna, rapor"],
      ["Araç kiralama", "Sözleşme, müsaitlik, fatura"],
      ["Lojistik", "Yük, çok durak, irsaliye, CMR, navlun"],
      ["Rezervasyon ve ön muhasebe", "Onay, iptal, kasa, gelir-gider"],
    ],
  },
  stack: {
    title: "Sektör standartlarıyla uyum",
    headers: ["Sistem", "İş değeri"],
    rows: [
      ["Arvento", "Araç GPS, son durum ve konum geçmişi"],
      ["Mobiliz", "Takip, iz, rapor ve araç komutları"],
      ["Streamax", "Kamera, alarm, olay ve kayıt"],
      ["UETDS", "Sefer bildirimi senkronu"],
      ["Netgsm", "SMS doğrulama"],
    ],
    note: "Yerli yazılım. Entegrasyonlar şirket bazında açılır.",
    close: [
      { title: "Kurumsal", text: "Operasyon, rota, araç, sürücü ve müşteriyi planlar." },
      { title: "Sürücü", text: "Canlı seferi başlatır, GPS paylaşır, durak durumunu işler." },
      { title: "Yolcu", text: "Canlı takip, istisna, rezervasyon ve ödeme ile hizmeti kullanır." },
    ],
  },
};
